### ISSUE TITLE
column names in `prefilter` function

### ISSUE THREAD

**Issue by thinkelman-ESA** [Tspaulding-ESA/filteRjsats#2]
Lines 54-57 in `prefilter`:

```
  temp$DateTime_Local = temp$DT
  temp$ReceiverSN = temp$R
  temp$Tag_Decimal = temp$D
  temp$Tag_Hex = temp$H
```
I would prefer to see this naming moved upstream to the `read_*` functions. Moreover, it appears that `read_tekno` does not produce a dataframe that inclues the column `R`.

**Comment by Tspaulding-ESA** [comment]
Fixed in latest push
